spring:
  application:
    name: customer-service

  datasource:
      url: jdbc:postgresql://localhost:5432/customerdb
      username: customer
      password: customer

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
    port: 8081